# Generated by Django 3.0.7 on 2020-07-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200710_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='jobpostdummy',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
