# Generated by Django 3.0.7 on 2020-07-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobpost_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserEmployer',
        ),
    ]
