# Generated by Django 3.0.7 on 2020-07-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200706_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployer',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
