# Generated by Django 3.0.7 on 2020-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useremployer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployer',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
